"""
deploy_model.py
---------------
Export the trained ML model to formats usable on edge hardware.

Two export targets:
    1. C++ code (m2cgen)  -> models/export/model_predictor.cpp
       For flashing directly onto ESP32 (no Python needed on device).

    2. ONNX               -> models/export/model.onnx
       For Raspberry Pi with onnxruntime (faster than scikit-learn pickle).

Usage:
    python src/deploy_model.py              # export best_model.pkl
    python src/deploy_model.py --target cpp # C++ only
    python src/deploy_model.py --target onnx # ONNX only
    python src/deploy_model.py --target both # both (default)

Requirements:
    pip install m2cgen skl2onnx onnx onnxruntime
"""

import os
import sys
import json
import joblib
import argparse
import numpy as np

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

EXPORT_DIR = os.path.join(project_root, "models", "export")


# -----------------------------------------------
#  LOAD MODEL
# -----------------------------------------------

def load(model_dir: str):
    model = joblib.load(os.path.join(model_dir, "best_model.pkl"))
    meta  = joblib.load(os.path.join(model_dir, "model_meta.pkl"))
    print(f"[LOAD] Model    : {meta.get('model_name', '?')}")
    print(f"       Accuracy : {meta.get('accuracy', 0):.4f}")
    print(f"       F1 macro : {meta.get('f1_macro', 0):.4f}")
    print(f"       Features : {len(meta.get('feature_names', []))}")
    return model, meta


# -----------------------------------------------
#  UNWRAP PIPELINE
# -----------------------------------------------

def unwrap_pipeline(model):
    """
    If model is a sklearn Pipeline, extract the classifier and scaler.
    m2cgen and skl2onnx need the raw estimator (or the full pipeline).
    """
    if hasattr(model, "named_steps"):
        # Pipeline: return as-is (m2cgen supports pipelines)
        return model
    return model


# -----------------------------------------------
#  EXPORT 1: C++ via m2cgen (for ESP32)
# -----------------------------------------------

def export_cpp(model, meta: dict, out_dir: str):
    """
    Generate pure C++ inference code from the model.
    The output file can be included in an Arduino / PlatformIO ESP32 sketch.

    No external libraries needed on ESP32 — pure float arithmetic.
    """
    try:
        import m2cgen as m2c
    except ImportError:
        print("[SKIP] m2cgen not installed. Run: pip install m2cgen")
        return None

    os.makedirs(out_dir, exist_ok=True)
    feature_names = meta.get("feature_names", [])
    label_map     = meta.get("label_map", {0: "Normal", 1: "Near-Crash", 2: "Crash"})
    n_classes     = meta.get("n_classes", 3)

    # Unwrap pipeline for m2cgen if it has a scaler stage
    clf = model
    if hasattr(model, "named_steps"):
        clf = model.named_steps.get("clf", model)

    print("\n[CPP] Generating C++ code via m2cgen...")
    try:
        cpp_code = m2c.export_to_c(clf)  # m2cgen C export (compatible with C++)
    except Exception as e:
        print(f"[CPP] m2c.export_to_c failed: {e}")
        try:
            cpp_code = m2c.export_to_java(clf)  # fallback
            print("[CPP] Fell back to Java export.")
        except Exception as e2:
            print(f"[CPP] m2cgen export failed entirely: {e2}")
            return None

    # Build the full Arduino-compatible header
    n_feats = len(feature_names)
    header = f"""// ============================================================
// Smart Airbag Helmet — ML Predictor (auto-generated by deploy_model.py)
// Model   : {meta.get('model_name', '?')}
// Accuracy: {meta.get('accuracy', 0):.4f}
// F1 macro: {meta.get('f1_macro', 0):.4f}
// Classes : {n_classes}  (0=Normal, 1=Near-Crash, 2=Crash)
// Features: {n_feats}
//
// Usage in ESP32 sketch:
//   #include "model_predictor.h"
//   float features[{n_feats}] = {{...}};  // fill from IMU window
//   double* result = predict(features);
//   int label = argmax(result, {n_classes});  // 2 = Crash -> deploy!
// ============================================================

#ifndef MODEL_PREDICTOR_H
#define MODEL_PREDICTOR_H

// Feature names (index matches the features[] array):
// """
    header += "\n// ".join([f"[{i:>3}] {name}" for i, name in enumerate(feature_names)])
    header += f"""

// Label map:
// 0 = Normal
// 1 = Near-Crash
// 2 = Crash

static int argmax(double* arr, int n) {{
  int idx = 0;
  for (int i = 1; i < n; i++) {{ if (arr[i] > arr[idx]) idx = i; }}
  return idx;
}}

"""
    footer = "\n#endif // MODEL_PREDICTOR_H\n"

    full_cpp = header + cpp_code + footer

    cpp_path = os.path.join(out_dir, "model_predictor.h")
    with open(cpp_path, "w", encoding="utf-8") as f:
        f.write(full_cpp)

    print(f"[CPP] Saved: {cpp_path}")
    print(f"      File size: {os.path.getsize(cpp_path) / 1024:.1f} KB")
    print(f"      Copy model_predictor.h into your ESP32 Arduino sketch folder.")
    return cpp_path


# -----------------------------------------------
#  EXPORT 2: ONNX (for Raspberry Pi)
# -----------------------------------------------

def export_onnx(model, meta: dict, out_dir: str):
    """
    Export the model to ONNX format for faster inference on Raspberry Pi.
    onnxruntime is ~2-5x faster than sklearn predict() for the same model.
    """
    try:
        from skl2onnx import convert_sklearn
        from skl2onnx.common.data_types import FloatTensorType
    except ImportError:
        print("[SKIP] skl2onnx not installed. Run: pip install skl2onnx onnx")
        return None

    os.makedirs(out_dir, exist_ok=True)
    feature_names = meta.get("feature_names", [])
    n_feats       = len(feature_names)

    print("\n[ONNX] Converting model to ONNX...")
    initial_types = [("float_input", FloatTensorType([None, n_feats]))]
    try:
        onnx_model = convert_sklearn(model, initial_types=initial_types,
                                     target_opset=17)
    except Exception as e:
        print(f"[ONNX] Conversion failed: {e}")
        return None

    onnx_path = os.path.join(out_dir, "model.onnx")
    with open(onnx_path, "wb") as f:
        f.write(onnx_model.SerializeToString())

    size_kb = os.path.getsize(onnx_path) / 1024
    print(f"[ONNX] Saved: {onnx_path}  ({size_kb:.1f} KB)")

    # Verify with onnxruntime
    try:
        import onnxruntime as rt
        sess = rt.InferenceSession(onnx_path)
        dummy = np.zeros((1, n_feats), dtype=np.float32)
        out   = sess.run(None, {"float_input": dummy})
        print(f"[ONNX] Verification OK. Output shape: {out[0].shape}")
        print(f"       Use on Raspberry Pi with onnxruntime for faster inference.")
    except ImportError:
        print("[ONNX] onnxruntime not installed (pip install onnxruntime). Cannot verify.")
    except Exception as e:
        print(f"[ONNX] Verification error: {e}")

    return onnx_path


# -----------------------------------------------
#  EXPORT FEATURE NAMES JSON (always)
# -----------------------------------------------

def export_feature_manifest(meta: dict, out_dir: str):
    """Save feature names and label map as JSON — useful for ESP32 firmware docs."""
    os.makedirs(out_dir, exist_ok=True)
    manifest = {
        "model_name"   : meta.get("model_name", "?"),
        "n_features"   : len(meta.get("feature_names", [])),
        "n_classes"    : meta.get("n_classes", 3),
        "label_map"    : {str(k): v for k, v in meta.get("label_map", {}).items()},
        "feature_names": meta.get("feature_names", []),
        "accuracy"     : round(meta.get("accuracy", 0), 4),
        "f1_macro"     : round(meta.get("f1_macro", 0), 4),
        "infer_ms"     : round(meta.get("infer_ms", 0), 4),
    }
    json_path = os.path.join(out_dir, "model_manifest.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(f"[JSON] Feature manifest saved: {json_path}")
    return json_path


# -----------------------------------------------
#  CLI
# -----------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Export ML model for edge deployment")
    parser.add_argument("--model-dir", default="models",  help="Directory with best_model.pkl")
    parser.add_argument("--target",    default="both",
                        choices=["cpp", "onnx", "both"], help="Export target format")
    args = parser.parse_args()

    model_dir = os.path.join(project_root, args.model_dir)
    model, meta = load(model_dir)

    print(f"\nExport directory: {EXPORT_DIR}")
    export_feature_manifest(meta, EXPORT_DIR)

    if args.target in ("cpp", "both"):
        export_cpp(model, meta, EXPORT_DIR)

    if args.target in ("onnx", "both"):
        export_onnx(model, meta, EXPORT_DIR)

    print("\nExport complete.")
    print("  model_predictor.h  -> copy to ESP32 Arduino sketch folder")
    print("  model.onnx         -> copy to Raspberry Pi, use with onnxruntime")
    print("  model_manifest.json -> feature ordering reference")


if __name__ == "__main__":
    main()
